### ISSUE TITLE
digitalcoin-qt.exe crashing.

### ISSUE THREAD

**Issue by Xandrah** [DGCDev/digitalcoin#32]
Faulting application name: digitalcoin-qt.exe, version: 3.0.1.0, time stamp: 0x000c0158
Faulting module name: digitalcoin-qt.exe, version: 3.0.1.0, time stamp: 0x000c0158
Exception code: 0x40000015
Fault offset: 0x0000000000f7dc6a
Faulting process ID: 0x21f8
Faulting application start time: 0x01d2a2f93303a322
Faulting application path: D:\digitalcoin-qt.exe
Faulting module path: D:\digitalcoin-qt.exe
Report ID: 2b17f76c-702f-413f-9a84-60f64a174640
Faulting package full name: 

We have tried this on numerous machines with the same result.

**Comment by ahmedbodi** [comment]
Needs a new build but bug fixed in latest commit
