### ISSUE TITLE
Win7 run DGCv3-win-x86.zip

### ISSUE THREAD

**Issue by kannr** [DGCDev/digitalcoin#34]
Microsoft Visual C++ Runtime Library
This application has requested the runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by Finn-Sionnach** [comment]
The only thing I've seen is to put 127.0.0.1 bittrex.com in your hosts file, while technically this works I have yet to see the wallet even begin to sync, but it "runs"

**Comment by Finn-Sionnach** [comment]
K got it from the older bitcointalk thread but apparently has more recent use...
https://www.coinexchange.io/network/peers/DGC
to the side is a convenient button "copy addnodes"

**Comment by kingkid3** [comment]
how do you add that to a host file i have it running from another drive so there is nothing in appdata/roaming

**Comment by Finn-Sionnach** [comment]
if you mean where to add the nodes it is wherever your digitalcoin.conf file is, if you mean where to block bittrex .. your hosts file it should be in windows/system32/drivers/etc   or search for hosts

**Comment by Finn-Sionnach** [comment]
sidenote: My wallet is all caught up now so this is working on win7

**Comment by ahmedbodi** [comment]
Needs a new build but bug fixed in latest commit
