### ISSUE TITLE
Bug Error Win 7 64 Bit

### ISSUE THREAD

**Issue by FndNur1Labs** [DGCDev/digitalcoin#36]
The VC++ i install is good and not bug....just this appear

Can you fixed it?
![rut_screenshot_2017-05-01_20-22-30](https://cloud.githubusercontent.com/assets/11433397/25578682/19b68780-2eac-11e7-92ce-e226f1ccb6c2.png)

All wallet is running good hmmmm

**Comment by gungit534** [comment]
add to hosts file
127.0.0.1 bittrex.com

my wallet works. (but 0 active connection all the time... )

**Comment by FndNur1Labs** [comment]
lol 0 conn that broken then @_@

**Comment by kingkid3** [comment]
this is copy and paste from #34 user Finn-Sionnach posted just wanted to share the help  

 https://www.coinexchange.io/network/peers/DGC
to the side is a convenient button "copy addnodes"

**Comment by ahmedbodi** [comment]
Needs a new build but bug fixed in latest commit
